<script type="text/javascript">
    //<![CDATA[
    function checkspsr() {
        new Ajax.Request('<?php echo $this->getSpsrAjaxCheckUrl() ?>', {
            method: 'get',
            onSuccess: function(transport) {
                if (transport.responseText) {
                    alert('Done');
                }
            }
        });
    }
    //]]>
</script>
<?php echo $this->getButtonHtml(); ?>